version: '3'
services:
  producer:
    build: .  # 使用 Dockerfile 来构建镜像
    container_name: producer_container
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      KAFKA_BROKER: "192.168.1.36:9092"  # Update with correct Kafka broker VM IP
    networks:
      - external_net
    logging:
      driver: "json-file"

  inference:
    build: .  # 使用 Dockerfile 来构建镜像
    container_name: inference_container
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      KAFKA_BROKER: "192.168.1.36:9092"  # Update with correct Kafka broker VM IP
    networks:
      - external_net
    logging:
      driver: "json-file"

networks:
  external_net:
    driver: bridge
