---
- name: "Install apt packages for cloud VMs"
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
      - python3
      - python3-pip
      - curl
      - git
      - unzip
      - build-essential
      - default-jre
      - ufw
      - net-tools
      - openssh-client
      - openssh-server
      - firewalld
      - nano
      - wget
    state: present
    update_cache: yes
  become: yes
  become_user: root
