---
# Install and configure firewalld, and set the necessary ports for Kafka and Zookeeper

- name: Install firewalld
  apt:
    name: firewalld
    state: present
    update_cache: yes

- name: Start and enable firewalld service
  systemd:
    name: firewalld
    state: started
    enabled: yes

# SSH
- name: Allow SSH (port 22)
  firewalld:
    port: 22/tcp
    permanent: true
    state: enabled
    immediate: yes

# Kafka Ports
- name: Allow Kafka default port (9092)
  firewalld:
    port: 9092/tcp
    permanent: true
    state: enabled
    immediate: yes

- name: Allow Kafka Broker Controller (port 9093)
  firewalld:
    port: 9093/tcp
    permanent: true
    state: enabled
    immediate: yes

- name: Allow Kafka Internal Communication (port 9094)
  firewalld:
    port: 9094/tcp
    permanent: true
    state: enabled
    immediate: yes

- name: Allow Kafka SSL Communication (port 9095)
  firewalld:
    port: 9095/tcp
    permanent: true
    state: enabled
    immediate: yes

# Zookeeper Ports
- name: Allow Zookeeper port (2181)
  firewalld:
    port: 2181/tcp
    permanent: true
    state: enabled
    immediate: yes

# HTTP/HTTPS Ports (if needed for web services)
- name: Allow HTTP (port 80)
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
    immediate: yes

- name: Allow HTTPS (port 443)
  firewalld:
    port: 443/tcp
    permanent: true
    state: enabled
    immediate: yes

- name: Reload firewalld to apply changes
  command: firewall-cmd --reload
